version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 9877:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build:
      context: .
      dockerfile: Dockerfile_django
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - 9001:8000
    environment:
      DEFAULT_PG_USER: ${POSTGRES_USER}
      DEFAULT_PG_DB: ${POSTGRES_DB}
      DEFAULT_PG_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db

volumes:
  postgres_data: